version: '2'
services:
  app:
    build: .
    image: <%= name %>
    ports:
      - "3000:3000"
    environment:
      - DEBUG=app*,-app:directoryrouter
    command:
      [ "node", "./dist/app.js" ]
